### ISSUE TITLE
MVP1 as milestone

### ISSUE THREAD

**Issue by gulprun** [China-Digital-Times-CDT/wepreserve#11]
- a skeleton landscape (background, working model, etc.)
- covering all relevant topics(sites) but not necessary to be complete in details
- clear and well proofread leading pages
- key demo of topics/sites on the working rationales, basic end user's experience

**Comment by gulprun** [comment]
Request for comments, @immartian @maklokgai, and sprint together in the coming days before 15th, thanks.

**Comment by gulprun** [comment]
Can we make a checklist for all the sites(of coz it would grow), with in #3 ?

**Comment by immartian** [comment]
agreed, we can make it like this:
- [ ] site 1
- [ ] site 2

**Comment by maklokgai** [comment]
I do have an offline list with the sites' full names in ZH and EN, acronyms, URLs, etc.
Any suggestion on how we can move it online? Sorry that I am not a familiar user of Github.
If any of you create a draft list, I should be able to update it quickly.

**Comment by maklokgai** [comment]
![image](https://user-images.githubusercontent.com/103475460/167693610-6ba470e7-9a4a-4947-ba29-ef48ce52e479.png)
![image](https://user-images.githubusercontent.com/103475460/167693664-d2a1617e-213c-4289-b734-999549dd493a.png)

Current site count: 30
This is also reflected in sites.md, but it's rudimentary.
IMHO, some sites are not perfect candidates, given they only have FB pages. If there are any candidates that should be excluded, please feel free to advise.

**Comment by gulprun** [comment]
Agreed, on some trivial(maybe a wrong word) sites/projects, but it's totally up to us to choose at this moment until some challengers are received by the community once we release them to wider publicity. 

Another tech issue, we are still in talking with FB to backup those Facebook-based pages, which is yet to have any content ready, unlike those independent web sites.

**Comment by gulprun** [comment]
Let's archive this as we have achieve the general goals in MVP1. All energies, draft works, collaborations and experiments will be moved forward to MVP2 to have a higher ceiling together with larger community. Cheers!
