### ISSUE TITLE
Candidates of web sites/institutions

### ISSUE THREAD

**Issue by gulprun** [China-Digital-Times-CDT/wepreserve#3]
We have some initial collections of the websites that have potential to be archived via the relics on internet, or may never be possible to save them back. Yet, please help nominate and/or contact those projects to save them even partially.

![image](https://user-images.githubusercontent.com/33362680/164127083-fe3e5502-a257-4936-a72f-21ec7c3f65cc.png)

**Comment by immartian** [comment]
- https://hongkongfp.com/2022/05/09/explainer-small-chinese-language-media-outlets-spring-up-as-hong-kongs-big-names-shut-down/
- A quest to link another project https://github.com/collection-news/collection-news/issues/37

**Comment by gulprun** [comment]
We just archived:  
- [ ] [Passion Time](https://www.passiontimes.hk/4.0/index.php)  (via https://hongkongfp.com/2022/05/18/hong-kong-national-security-police-demand-online-outlet-remove-sensitive-content-founder-says/) 
- [ ]
