### ISSUE TITLE
Logo, background, domain names , etc. 

### ISSUE THREAD

**Issue by gulprun** [China-Digital-Times-CDT/wepreserve#5]
We made a logo with this online tool, https://engfto.com/index/animated_neon_text_maker/0-27

![savehkonline](https://user-images.githubusercontent.com/33362680/164360796-01af7aac-348e-4a6a-91aa-ef25e3581e78.gif)

It's definitely not perfect while love to see anyone loves to contribute a real artistic design.

**Comment by immartian** [comment]
How about white background? 
![savehkonline_wbg](https://user-images.githubusercontent.com/81030/164413523-86cdbf4d-8b33-4a56-8897-a5189442d0fe.gif)

**Comment by gulprun** [comment]
looks good, how about this one
![download](https://user-images.githubusercontent.com/33362680/164417974-d0ac3826-5172-4651-af44-7800cfb85166.gif)


Configures:
![image](https://user-images.githubusercontent.com/33362680/164417936-1a35d98d-1668-41bc-b287-48ebcc6f9e68.png)
![image](https://user-images.githubusercontent.com/33362680/164417883-da9b26d4-5c90-482e-aa8d-feccafad0ce5.png)

**Comment by maklokgai** [comment]
![image](https://user-images.githubusercontent.com/103475460/165342531-567cc315-5a9a-43a2-8318-a84c351061dc.png)

Just used Photoshop to create this - it looks weird to me, but just wanted to share it in case it can spark some ideas.
Yellow and black are the two colours of the protest

**Comment by immartian** [comment]
I like the yellow/black hint, which's better to meet the movement(but should we?)

it'd be useable now if it has a transparent background to make it not odd with the singular theme of Dendron(which is not customizable at this moment. 

Let's call a designer to  from here while keeping trials.

**Comment by gulprun** [comment]
> Just used Photoshop to create this - it looks weird to me, but just wanted to share it in case it can spark some ideas.

can you share a ps file and we may put to the site for a trial; a transparent background is necessary.

**Comment by maklokgai** [comment]
Sorry, just pressed the wrong button. Github doesn't allow me to upload PSD file, any advice on how to do it?
Uploading the PNG file just FYI:
![Logo_trial](https://user-images.githubusercontent.com/103475460/165778153-b76ed211-8b01-4fe9-a356-5ea5c347c8d7.png)

**Comment by gulprun** [comment]
Before we release our MVP1(#11 ), we may consider a new repo to be independent from our patron. Consequently, we may need a top-level domain name for publicity in a long run. Please help brainstorm some ideas, @maklokgai @immartian. 

some available candidates:
- shok.news
- shok.homes

**Comment by gulprun** [comment]
looks not bad... we can find a designer to fine-tune it along the path
![image](https://user-images.githubusercontent.com/33362680/168941852-05321efa-6c31-4f48-b26f-10946b3599e0.png)

**Comment by gulprun** [comment]
> savehk.org
the domain is taken. 

savehkonline.org is still available

**Comment by gulprun** [comment]
> savehkonline.org is still available
Domain acquired, will put into action soon, within MVP2
